# backend/parsers.py

def parse_outline(outline: str):
    """
    Parses an outline string generated by OpenAI into a course title and list of modules.
    Each module is a dict with keys 'module_name' and 'lessons' (a list of lesson names).

    Expected outline format:
    
    Course Title: <course name>
    
    Module 1: <Module Name>
    - Lesson: <Lesson Name 1>
    - Lesson: <Lesson Name 2>
    
    Module 2: <Module Name>
    - Lesson: <Lesson Name 1>
    - Lesson: <Lesson Name 2>
    
    This is a basic parser and can be adjusted to your specific format.
    """
    lines = outline.splitlines()
    course_title = ""
    modules = []
    current_module = None

    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.lower().startswith("course title:"):
            course_title = line.split(":", 1)[1].strip()
        elif line.lower().startswith("module"):
            if current_module is not None:
                modules.append(current_module)
            current_module = {"module_name": line, "lessons": []}
        elif line.lower().startswith("- lesson:"):
            if current_module is not None:
                # Extract lesson name after the colon
                lesson_name = line.split(":", 1)[1].strip()
                current_module["lessons"].append(lesson_name)
    if current_module is not None:
        modules.append(current_module)
    return course_title, modules
